#!/usr/bin/env bash
set -o nounset # exit on unbound variables
set -o errexit # exit on any non-true return val
source "$_IPM_ROOT/share/ipm/utils.sh"

update_modules() {
  local rvl=$1
  echo "${yellow}${underline}RVL: $rvl${reset}"
  cd "$basedir/rvl/$rvl/stage"
  ls -d */ | while read module; do
    echo "${cyan}${underline}MODULE: $module${reset}"
    cd "$module"
    if [[ "$(git symbolic-ref -q --short HEAD 2>/dev/null)" == "master" ]]; then
      igit pull
    else
      echo "${red}Not on master branch, skipping...${reset}"
    fi
    cd - >/dev/null
  done
}

cwd=$(pwd)
for rvl in $(get_rvls ${1:-all}); do
  update_modules $rvl
done
cd $cwd
