#!/usr/bin/env php
<?php
# Set appropriate IPM env
$_IPM_ROOT = getenv('_IPM_ROOT');
require_once "$_IPM_ROOT/share/ipm/utils.php";
$rvl = set_ipm_base_dir(@$argv[1] ?: null);

# Load IPM env
require_once '/etc/ipm.conf';

require_once '/opt/src/boris/lib/autoload.php';
$boris = new \Boris\Boris("ipm-{$rvl}> ");
$boris->start();
