#!/usr/bin/env bash
set -o nounset # exit on unbound variables
set -o errexit # exit on any non-true return val
source "$_IPM_ROOT/share/ipm/utils.sh"

show_branches() {
  local rvl=$1
  echo "${yellow}${underline}RVL: $rvl${reset}"
  cd "$basedir/rvl/$rvl/stage"
  ls -d */ | while read module; do
    cd "$module"
    output="${cyan}${underline}MODULE: $module${reset}"
    if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
      output="${output} ${red}(dirty)${reset}"
    fi
    echo $output
    git branch
    cd - >/dev/null
  done
}

cwd=$(pwd)
for rvl in $(get_rvls ${1:-all}); do
  show_branches $rvl
done
cd $cwd
