#!/usr/bin/env bash
set -o nounset # exit on unbound variables
set -o errexit # exit on any non-true return val
source "$_IPM_ROOT/share/ipm/utils.sh"

update_tags() {
  local rvl=$1
  echo "${yellow}${underline}RVL: $rvl${reset}"
  cd "$basedir/rvl/$rvl"
  # global -vu
  (
  for auto in mod/*/.autoload; do
      module=$(dirname "$auto")
      find "$module/src" -name '*.php' -print
  done
  ) > gtags.files
  gtags -v 2>&1 | grep -v extracting
}

cwd=$(pwd)
for rvl in $(get_rvls ${1:-all}); do
  update_tags $rvl
done
cd $cwd
