#!/usr/bin/env bash
set -o nounset # exit on unbound variables
set -o errexit # exit on any non-true return val
source "$_IPM_ROOT/share/ipm/utils.sh"

prjdir="$basedir/rvl/$1"
[[ -d "$prjdir" ]] && err "$prjdir already exists"

echo "${yellow}${underline}RVL: $1${reset}"
echo "Creating directory structure"
mkdir -p "$prjdir"/{Attachments,Logs,demos,mod,monitor_rrd,stage,tmp,tripwire,wiki,wiki_upload}

echo "Copying shared files"
sed "s/%{http_port}/$(get_port $1)/" "$basedir/share/ipm.conf" > "$prjdir/ipm.conf"

echo "Linking shared modules"
ln -s "$basedir/share/stage/system_scripts" "$prjdir/system_scripts"
ln -s "$basedir/share/stage/img-HEAD" "$prjdir/mod/img"

echo "Cloning new modules..."
echo "${cyan}${underline}MODULE: 3rdparty_2014${reset}"
cd "$prjdir/stage" && igit init 3rdparty_2014       $1 && cd "$prjdir" && ln -s "$prjdir/stage/3rdparty_2014-$1"       "$prjdir/mod/3rdparty"
echo "${cyan}${underline}MODULE: ipm_core_2014${reset}"
cd "$prjdir/stage" && igit init ipm_core_2014       $1 && cd "$prjdir" && ln -s "$prjdir/stage/ipm_core_2014-$1"       "$prjdir/mod/core"
echo "${cyan}${underline}MODULE: ipm_db${reset}"
cd "$prjdir/stage" && igit init ipm_db              $1 && cd "$prjdir" && ln -s "$prjdir/stage/ipm_db-$1"              "$prjdir/mod/db"
echo "${cyan}${underline}MODULE: ipm_interfaces_2014${reset}"
cd "$prjdir/stage" && igit init ipm_interfaces_2014 $1 && cd "$prjdir" && ln -s "$prjdir/stage/ipm_interfaces_2014-$1" "$prjdir/mod/interfaces"
echo "${cyan}${underline}MODULE: userfacing${reset}"
cd "$prjdir/stage" && igit init userfacing          $1 && cd "$prjdir" && ln -s "$prjdir/stage/userfacing-$1"          "$prjdir/mod/userfacing"

